services:
  database:
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB
      POSTGRES_PASSWORD: $PG_PASS
    ports:
      - "9969:5432"
    image: postgres:16.4-alpine3.20
    volumes:
      - ./pgdata-non-pay:/var/lib/postgresql/data/
      - ./database:/docker-entrypoint-initdb.d/
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $PG_USER -d $PG_DB" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true